### ISSUE TITLE
Video doesn't work

### ISSUE THREAD

**Issue by sopharsogood** [learn-co-curriculum/oo-cli-data-gem-walkthrough#6]
The video doesn't load or play. It just displays "(!) This video is unavailable."

**Comment by ihollander** [comment]
Hi @sopharsogood  - thanks for flagging this issue. This video along with the others were recorded by an instructor who is no longer with Flatiron and have subsequently been removed from YouTube so unfortunately we no longer have access to them. We've removed these videos in Canvas so future students won't see the broken video links.
